name: build
on: workflow_dispatch 
jobs: 
  first-job:
    runs-on: [self-hosted, macos-12]
    steps: 
      - name: Print greeting
        run: echo "hello world"
      - name: Print goodbye 
        run: echo "goodbye" 
